apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: eh-5ll8ua-java-springboot
  janus-idp.io/tekton: eh-5ll8ua-java-springboot
  backstage.io/kubernetes-id: eh-5ll8ua-java-springboot
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: eh-5ll8ua-java-springboot
resources:
- deployment.yaml
- route.yaml
- service.yaml
